### ISSUE TITLE
Comprobación de etiquetas, textos y tooltips en varios idiomas

### ISSUE THREAD

**Issue by ANavarro96** [ANavarro96/catmedit-vv#2]
Cuando se pulsa sobre una pestaña '+' en el árbol de metadatos, no muestra nada porque no hay, entonces no debería aparecer ese '+'. No hay restricciones en los campos de introducción de datos. A la hora de crear o borrar un dato multievaluado, no pregunta, crea o borra directamente.

**Comment by miguel-latre** [comment]
1. Cuando se ha creado este _issue_, podría haberse etiquetado como «enhancement» en lugar de «bug» (aunque esto es solo mi impresión, que además estará influenciada por el hecho de que estoy más próximo al equipo de desarrollo del CatMDEdit que vosotros).
2. El etiquetado del _issue_ como «invalid» debería ir acompañado de una explicación de porqué el _bug_/mejora no es válido. ¿No se querría haberlo cerrado con la etiqueta «wontfix»? (En un entorno real, de todas formas, el cierre con «wontfix» también debería estar justificado.)

**Comment by miguel-latre** [comment]
Faltaría haber puesto una referencia al _id_ en la hoja de cálculo de las pruebas del CatMDEdit, tal y como se pedía en el enunciado. En este caso, se trataría de la prueba 2.1.
