### ISSUE TITLE
Utilidad de rectángulo envolvente geográfico

### ISSUE THREAD

**Issue by JorgeBlazHer** [ANavarro96/catmedit-vv#3]
En CentOS no abre el mapa del mundo ni el de comunidades de España cuando se selecciona para insertar coordenadas como metadatos.
En windows solo permite seleccionar con el cuadro en el mapa del mundo, en el resto no.

**Comment by miguel-latre** [comment]
Habría que haber añadido la etiqueta «wontfix» al cerrarlo, ya que no se va a arreglar (porque no vamos a trabajar más con el CatMDEdit en esta asignatura).
