### ISSUE TITLE
Cambios en metadatos multilingües

### ISSUE THREAD

**Issue by JorgeBlazHer** [ANavarro96/catmedit-vv#8]
Cuando se replica una plantilla en otro idioma, lo genera con el mismo id y cuando se refresca la lista borra la mas antigua.

**Comment by miguel-latre** [comment]
1. El etiquetado del issue como «invalid» debería ir acompañado de una explicación de porqué el bug/mejora no es válido. ¿No se querría haberlo cerrado con la etiqueta «wontfix»? (En un entorno real, de todas formas, el cierre con «wontfix» también debería estar justificado.)
2. Este _issue_, en lugar de inválido, es en realidad un duplicado de #11.
