### ISSUE TITLE
Comprobación de visualización en HTML

### ISSUE THREAD

**Issue by Gonzakick** [ANavarro96/catmedit-vv#9]
Al comprobar que se ofrecen todas las posibilidades de visualización HTML para este estándar, y que el metadato se muestra correctamente, en windows 10 la pestaña del html no muestra bien los elementos, ya que ocurren varios bugs visuales: se dibujan varias líneas donde no tendría que haber, se duplican…

**Comment by miguel-latre** [comment]
Faltaría la etiqueta «bug».
